site_name: scikit-eo

site_url: https://ytarazona.github.io/scikit-eo

repo_url: https://ytarazona.github.io/scikit-eo

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    icon:
        repo: fontawesome/brands/github
    logo: images/logo.png
    favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"

#theme: readthedocs

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          #execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Get Started: get-started.md
    - Tutorials: tutorials.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Report Issues: https://github.com/ytarazona/scikit-eo/issues
    - API Reference:
          - mla module: mla.md
          - calmla module: calmla.md
          - rkmeans module: rkmeans.md
          - calkmeans module: calkmeans.md
          - pca module: pca.md
          - atmosCorr module: atmosCorr.md
          - deeplearning module: deeplearning.md
          - linearTrend module: linearTrend.md
          - fusionrs module: fusionrs.md
          - sma module: sma.md
          - tassCap module: tassCap.md
          - plot module: plot.md
          - writeRaster module: writeRaster.md
          - process module: process.md
